name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # 매일 00:00 UTC에 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: aebonlee  # ← 본인 GitHub ID로 변경
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update snake animation"
          add: "dist/github-contribution-grid-snake.svg"
